### ISSUE TITLE
[BUG] Event generation fails for FFImageLoading

### ISSUE THREAD

**Issue by winterdouglas** [reactiveui/Pharmacist#88]
**Describe the bug**
When you install Pharmacist in a Xamarin.Forms project that has FFImageLoading it makes the event generation to fail. It can't basically handle the events that FF exposes cause they are in a static class with all the events.

**Steps To Reproduce**
1. Install Pharmacist latest (1.2.2) into a Xamarin.Forms app that has FFImageLoading as well
2. Build the project
3. It fails on building

**Expected behavior**
The events should be generated. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1329194/70464825-fc2b6700-1abf-11ea-9098-d4a737cb374d.png)

**Comment by glennawatson** [comment]
I'm doing some work on Pharmacist today so will add this to the test bed.

**Comment by glennawatson** [comment]
I believe this problem has been solved since it's not happening for me anymore.

**Comment by winterdouglas** [comment]
Hi @glennawatson.
I'm gonna have a try tomorrow to see what happens.

Thank you!

**Comment by winterdouglas** [comment]
Hey @glennawatson, sorry for the late answer, I tried here again with the version 1.5.3 and FF latest and the same issue still happens.

Just to mention, the packages I have installed here are exactly:
- `Pharmacist.MsBuild 1.5.3`
- `Pharmacist.Common 1.5.3`
- `Xamarin.FFImageLoading.Forms 2.4.11.982`
- `Xamarin.FFImageLoading.Svg.Forms 2.4.11.982`
- `Xamarin.FFImageLoading.Transformations 2.4.11.982`

The one that produces the issue to me is the `Xamarin.FFImageLoading.Forms` itself.

This is what gets generated:

[Pharmacist.NuGet.cs.txt](https://github.com/reactiveui/Pharmacist/files/4025530/Pharmacist.NuGet.cs.txt)

**Comment by glennawatson** [comment]
@winterdouglas what does your project look like? Are you doing this in your .net standard shared project or on the final project?

**Comment by winterdouglas** [comment]
These packages are installed in the .net standard forms project itself, not in the platform projects. Nothing special about them.

Here's a sample project where the error happens:
[PharmacistFFImageLoading.zip](https://github.com/reactiveui/Pharmacist/files/4025951/PharmacistFFImageLoading.zip)
It's a basic Xamarin.Forms app and the only packages that are installed there are `FFImageLoading.Forms` and `Pharmacist.MsBuild` and `Pharmacist.Common`.

**Comment by glennawatson** [comment]
This was solved with 1.5.14 release.

**Comment by winterdouglas** [comment]
Gonna give it a try and will let you know. Thanks @glennawatson
